version: '3'

services:
  db:
    image: postgres:alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: contact
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234567
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  app:
    build:
      context: .  # Contexto de build aponta para a raiz do projeto
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/contact
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1234567
    depends_on:
      - db
    restart: always

volumes:
  postgres_data: