version: '3.8'
services:
  dbpostgresql:
    image: postgres:alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=1234567
      - POSTGRES_USER=postgres
      - POSTGRES_DB=contact
    command:
      - -p ${DB_PORT:-5432}